### ISSUE TITLE
＊＝じゃなくて＋＝にすればすこしは加速抑えられるのではないだろうか

### ISSUE THREAD

**Issue by c0b21053** [c0b2103990/ProjExD#10]
https://github.com/c0b2103990/ProjExD/blob/d8eea31671670cbc7d8e2adbf4222c21b8edb0e7/ex04/dodge_bomb.py#L75

**Comment by c0b2103990** [comment]
コメントありがとうございます。
+= にしたらより早くなり、軌道もおかしくなりましたので、使わなっかたです。
