### ISSUE TITLE
加速を抑えるのは *= 1.0005ぐらいで設定してみてください

### ISSUE THREAD

**Issue by 8170** [c0b2103990/ProjExD#11]
https://github.com/c0b2103990/ProjExD/blob/d8eea31671670cbc7d8e2adbf4222c21b8edb0e7/ex04/dodge_bomb.py#L74

**Comment by c0b2103990** [comment]
コメントありがとうございます。
1.0005にしても速かったので、1.0001にしましたら、丁度良くなりました。
